Revert "pass debian release name without --release"
This reverts commit 757160b815fe24ef8a84bf8ed710712036fe07e3.

diff --git a/holodev b/holodev
--- a/holodev
+++ b/holodev
@@ -66,9 +66,9 @@ for i in "$@"; do
       GIT_BRANCH=$2
       shift 2
       ;;
-    stable|testing|sid|squeeze|wheezy|jessie|stretch)
-      DEBIAN_RELEASE=$i
-      shift
+    --release)
+      DEBIAN_RELEASE=$2
+      shift 2
       ;;
     --version)
       shift
@@ -95,6 +95,9 @@ for i in "$@"; do
     *)
       if [ -n $previous ] && [ "$previous" = '--arch' ]; then
         # we don't need validation for --arch param
+        true
+      elif [ -n $previous ] && [ "$previous" = '--release' ]; then
+        # we don't need validation for --release param
         true
       elif [ -n $previous ] && [ "$previous" = '--branch' ]; then
         # we don't need validation for --branch param
@@ -132,8 +135,8 @@ error() {
   echo "${RED}[HOLODEV] $@${ENDCOLOR}"
 }
 
-if $INVALID_OPTIONS; then
-  error "invalid options" >&2
+if [ -z $COMMAND ] || $INVALID_OPTIONS; then
+  error "missing command or invalid options" >&2
   COMMAND=help
 fi
 
